### ISSUE TITLE
the code report the pyglet issues with OpenGL

### ISSUE THREAD

**Issue by wuyohee2004** [MorvanZhou/Reinforcement-learning-with-tensorflow#13]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 916, in _bootstrap_inne
r
    self.run()
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "arm_a3c_RL.py", line 201, in <lambda>
    job = lambda: worker.work()
  File "arm_a3c_RL.py", line 136, in work
    self.env.render()
  File "C:\Code\python_code\RL\arm_env.py", line 72, in render
    self.viewer = Viewer(*self.viewer_xy, self.arm_info, self.point_info, self.p
oint_l, self.mouse_in)
  File "C:\Code\python_code\RL\arm_env.py", line 115, in __init__
    super(Viewer, self).__init__(width, height, resizable=False, caption='Arm',
vsync=False)  # vsync=False to not use the monitor FPS
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyglet\window\win32\__init__.
py", line 131, in __init__
    super(Win32Window, self).__init__(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyglet\window\__init__.py", l
ine 504, in __init__
    config = screen.get_best_config(template_config)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyglet\canvas\base.py", line
161, in get_best_config
    configs = self.get_matching_configs(template)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyglet\canvas\win32.py", line
 33, in get_matching_configs
    configs = template.match(canvas)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyglet\gl\win32.py", line 25,
 in match
    return self._get_arb_pixel_format_matching_configs(canvas)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyglet\gl\win32.py", line 98,
 in _get_arb_pixel_format_matching_configs
    nformats, pformats, nformats)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyglet\gl\lib_wgl.py", line 9
5, in __call__
    result = self.func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyglet\gl\lib.py", line 62, i
n MissingFunction
    raise MissingFunctionException(name, requires, suggestions)
**pyglet.gl.lib.MissingFunctionException: wglChoosePixelFormatARB is not exported
by the available OpenGL driver.  ARB_pixel_format is required for this functiona
lity.**

**Comment by EliasHasle** [comment]
I have encountered the same problem when trying to render to pyglet windows in two different threads. The first thread works, while the second fails with that exact error message.
