### ISSUE TITLE
每次运行实例都会出现中断，产生keyerror：

### ISSUE THREAD

**Issue by ZQYyyo** [MorvanZhou/Reinforcement-learning-with-tensorflow#207]
错误如下
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\pandas\core\indexes\base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 98, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index_class_helper.pxi", line 89, in pandas._libs.index.Int64Engine._check_type
KeyError: -8.68761673816986e-08

**Comment by nmf0920** [comment]
我也是这样，请问你找到解决办法了吗？
