### ISSUE TITLE
Try to apply RL_brain to new gym enviroment

### ISSUE THREAD

**Issue by nik31096** [MorvanZhou/Reinforcement-learning-with-tensorflow#51]
Hello Morvan!
I'm new to RL and OpenAI Gym.
I'm exiting of your work, you are great RL programmer!
I've a question: I've executed your Cartpole-v0 with RL_brain and it works fine.
And I wonder if I can apply your RL_brain to my new enviroment, with is an extension of Cartpole-v0.
The difference between v0 and my_env is more wide screen and my pole starts from the bottom.
My aim is to learn the system how to reach the top as Mountain_Car do, making right and left moves in right time. I've tried that, but got this bug:
Original exception was:
Traceback (most recent call last):
  File "/home/nik/PycharmProjects/diplom/CartPole-v1.py", line 50, in <module>
    RL.store_transition(observation, action, reward, observation_)
  File "/home/nik/PycharmProjects/diplom/RL_brain.py", line 117, in store_transition
    self.memory[index, :] = transition
ValueError: could not broadcast input array from shape (10) into shape (6)
My Cartole-v1 is here:
"""
Deep Q network,
Using:
Tensorflow: 1.6
gym: 0.10.5
"""

import sys
import gym
import gymCartpoleBottom.gym_cartpolebottom
from RL_brain import DeepQNetwork

try:
env = gym.make('CartpoleBottom-v0')
except:
print("No registered env with id: CartpoleBottom-v0")
sys.exit()

env = env.unwrapped

print(env.action_space)
print(env.observation_space)
print(env.observation_space.high)
print(env.observation_space.low)

RL = DeepQNetwork(n_actions=2, n_features=2, learning_rate=0.001, e_greedy=0.9,
replace_target_iter=300, memory_size=30000,
e_greedy_increment=0.0002,)

total_steps = 0

for i_episode in range(10):
observation = env.reset()
ep_r = 0
while True:
env.render()

    action = RL.choose_action(observation)

    observation_, reward, done, info = env.step(action)
    print(observation_)

    position, velocity, _, _ = observation_

    # the higher the better
    reward = abs(position - (-0.5))     # r in [0, 1]

    RL.store_transition(observation, action, reward, observation_)

    if total_steps > 1000:
        RL.learn()

    ep_r += reward
    if done:
        get = '| Get' if observation_[0] >= env.unwrapped.goal_position else '| ----'
        print('Epi: ', i_episode,
              get,
              '| Ep_r: ', round(ep_r, 4),
              '| Epsilon: ', round(RL.epsilon, 2))
        break

    observation = observation_
    total_steps += 1
RL.plot_cost()

Could you help me please? I really struggle of this already(((
I would be very grateful!
With best wishes,
Nik

**Comment by nik31096** [comment]
My Cartole-v1 is here:
"""
Deep Q network,
Using:
Tensorflow: 1.6
gym: 0.10.5
"""

import sys
import gym
import gymCartpoleBottom.gym_cartpolebottom
from RL_brain import DeepQNetwork


try:
    env = gym.make('CartpoleBottom-v0')
except:
    print("No registered env with id: CartpoleBottom-v0")
    sys.exit()

env = env.unwrapped

print(env.action_space)
# print(env.observation_space)
# print(env.observation_space.high)
# print(env.observation_space.low)

RL = DeepQNetwork(n_actions=2, n_features=2, learning_rate=0.001, e_greedy=0.9,
                  replace_target_iter=300, memory_size=30000,
                  e_greedy_increment=0.0002,)

total_steps = 0


for i_episode in range(10):
    observation = env.reset()
    ep_r = 0
    while True:
        env.render()

        action = RL.choose_action(observation)

        observation_, reward, done, info = env.step(action)
        print(observation_)

        position, velocity, _, _ = observation_

        # the higher the better
        reward = abs(position - (-0.5))     # r in [0, 1]

        RL.store_transition(observation, action, reward, observation_)

        if total_steps > 1000:
            RL.learn()

        ep_r += reward
        if done:
            get = '| Get' if observation_[0] >= env.unwrapped.goal_position else '| ----'
            print('Epi: ', i_episode,
                  get,
                  '| Ep_r: ', round(ep_r, 4),
                  '| Epsilon: ', round(RL.epsilon, 2))
            break

        observation = observation_
        total_steps += 1

RL.plot_cost()
